package io.github.youndie.kachok.ui.main

import io.github.youndie.kachok.ui.list.TorrentRowModel
import io.github.youndie.kachok.ui.list.TorrentState

/**
 * The design's own sixteen torrents, in the design's own order, with the design's own numbers.
 *
 * Transcribed from the row markup of `docs/design/kachok Phase 2 Desktop.dc.html`, so a difference
 * between the golden and `docs/design/screens/main-window.png` is a difference in drawing rather
 * than in data. The first one is selected, which is the state the design draws it in.
 */
internal val designTorrents: List<TorrentRowModel> =
    listOf(
        TorrentRowModel(
            name = "debian-13.1.0-amd64-DVD-1.iso",
            size = "3.70 GiB",
            progress = 0.78f,
            percent = "78%",
            down = "4 312",
            up = "812",
            connected = 24,
            unchoked = 4,
            outstanding = 61,
            ratio = "0.11",
            eta = "3m 20s",
            state = TorrentState.Downloading,
            selected = true,
        ),
        TorrentRowModel(
            name = "e4f2c1a9d3b7…6f08",
            size = "—",
            progress = null,
            percent = "—",
            down = "0",
            up = "0",
            connected = 6,
            unchoked = 0,
            outstanding = 0,
            ratio = "—",
            eta = "—",
            state = TorrentState.Metadata,
        ),
        TorrentRowModel(
            name = "archlinux-2026.09.01-x86_64.iso",
            size = "1.22 GiB",
            progress = 0.27f,
            percent = "27%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "1.84",
            eta = "—",
            state = TorrentState.Checking,
        ),
        TorrentRowModel(
            name = "Sintel-2010-1080p-DCP.tar",
            size = "14.6 GiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "1 480",
            connected = 31,
            unchoked = 4,
            outstanding = 0,
            ratio = "2.07",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "fedora-workstation-45-x86_64.iso",
            size = "2.41 GiB",
            progress = 0.52f,
            percent = "52%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "0.44",
            eta = "—",
            state = TorrentState.Paused,
        ),
        TorrentRowModel(
            name = "Tears-of-Steel-4k-master.mkv",
            size = "8.03 GiB",
            progress = 0.91f,
            percent = "91%",
            down = "96",
            up = "0",
            connected = 3,
            unchoked = 0,
            outstanding = 4,
            ratio = "0.02",
            eta = "—",
            state = TorrentState.Stopping,
        ),
        TorrentRowModel(
            name = "openSUSE-Leap-16.1-DVD-x86_64.iso",
            size = "4.38 GiB",
            progress = 0.63f,
            percent = "63%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "0.19",
            eta = "—",
            state = TorrentState.Error,
        ),
        TorrentRowModel(
            name = "ubuntu-26.04-desktop-amd64.iso",
            size = "5.14 GiB",
            progress = 0.12f,
            percent = "12%",
            down = "9 604",
            up = "204",
            connected = 42,
            unchoked = 4,
            outstanding = 64,
            ratio = "0.01",
            eta = "8m 04s",
            state = TorrentState.Downloading,
        ),
        TorrentRowModel(
            name = "Blender-4.6-macos-arm64.dmg",
            size = "412 MiB",
            progress = 0.96f,
            percent = "96%",
            down = "1 208",
            up = "96",
            connected = 11,
            unchoked = 2,
            outstanding = 18,
            ratio = "0.23",
            eta = "14s",
            state = TorrentState.Downloading,
        ),
        TorrentRowModel(
            name = "Big-Buck-Bunny-1080p-h264.mov",
            size = "691 MiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "348",
            connected = 8,
            unchoked = 3,
            outstanding = 0,
            ratio = "6.71",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "nixos-25.11-minimal-x86_64.iso",
            size = "1.04 GiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "64",
            connected = 5,
            unchoked = 1,
            outstanding = 0,
            ratio = "1.36",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "alpine-standard-3.24-x86_64.iso",
            size = "218 MiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "12",
            connected = 2,
            unchoked = 1,
            outstanding = 0,
            ratio = "11.4",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "gimp-3.2.4-source.tar.xz",
            size = "48.2 MiB",
            progress = 0.41f,
            percent = "41%",
            down = "612",
            up = "0",
            connected = 7,
            unchoked = 2,
            outstanding = 22,
            ratio = "0.00",
            eta = "47s",
            state = TorrentState.Downloading,
        ),
        TorrentRowModel(
            name = "void-live-x86_64-musl-20260812.iso",
            size = "1.61 GiB",
            progress = 0.07f,
            percent = "7%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "0.00",
            eta = "—",
            state = TorrentState.Paused,
        ),
        TorrentRowModel(
            name = "Cosmos-Laundromat-1080p.mkv",
            size = "2.88 GiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "508",
            connected = 14,
            unchoked = 4,
            outstanding = 0,
            ratio = "3.42",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "kachok-0.1.0-linux-amd64.tar.gz",
            size = "63.0 MiB",
            progress = 1.00f,
            percent = "100%",
            down = "0",
            up = "28",
            connected = 3,
            unchoked = 1,
            outstanding = 0,
            ratio = "18.9",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
    )

/** The status line under them, likewise. */
internal val designStatus: SessionStatus =
    SessionStatus(
        down = "15 736 KiB/s",
        up = "3 152 KiB/s",
        torrents = "16 torrents, 7 seeding, 2 paused",
        dht = "DHT 214 nodes",
        port = "port 6881 listening",
        heap = "heap 41 / 128 MiB",
    )

/** And the banner, whose second half is the exception the engine actually throws. */
internal const val DEGRADED_SUMMARY: String = "One session is degraded."

internal const val DEGRADED_DETAIL: String =
    "writer loop failed: java.nio.channels.ClosedChannelException"
