package io.github.youndie.kachok.ui.list

/**
 * The seven states with the design's own numbers, names and order.
 *
 * Shared by the golden and by `RowColorsTest`, so that the sheet a human compares against
 * `docs/design/screens/main-window.png` and the table a machine checks the hexes of are the same
 * seven rows. Two lists would drift, and the one that drifted would be the untested one.
 */
internal val designRows: List<TorrentRowModel> =
    listOf(
        TorrentRowModel(
            name = "e4f2c1a9d3b7…6f08",
            size = "—",
            progress = null,
            percent = "—",
            down = "0",
            up = "0",
            connected = 6,
            unchoked = 0,
            outstanding = 0,
            ratio = "—",
            eta = "—",
            state = TorrentState.Metadata,
        ),
        TorrentRowModel(
            name = "archlinux-2026.09.01-x86_64.iso",
            size = "1.22 GiB",
            progress = 0.27f,
            percent = "27%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "1.84",
            eta = "—",
            state = TorrentState.Checking,
        ),
        TorrentRowModel(
            name = "debian-13.1.0-amd64-DVD-1.iso",
            size = "3.70 GiB",
            progress = 0.78f,
            percent = "78%",
            down = "4 312",
            up = "812",
            connected = 24,
            unchoked = 4,
            outstanding = 61,
            ratio = "0.11",
            eta = "3m 20s",
            state = TorrentState.Downloading,
        ),
        TorrentRowModel(
            name = "Sintel-2010-1080p-DCP.tar",
            size = "14.6 GiB",
            progress = 1f,
            percent = "100%",
            down = "0",
            up = "1 480",
            connected = 31,
            unchoked = 4,
            outstanding = 0,
            ratio = "2.07",
            eta = "∞",
            state = TorrentState.Seeding,
        ),
        TorrentRowModel(
            name = "fedora-workstation-45-x86_64.iso",
            size = "2.41 GiB",
            progress = 0.52f,
            percent = "52%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "0.44",
            eta = "—",
            state = TorrentState.Paused,
        ),
        TorrentRowModel(
            name = "Tears-of-Steel-4k-master.mkv",
            size = "8.03 GiB",
            progress = 0.91f,
            percent = "91%",
            down = "96",
            up = "0",
            connected = 3,
            unchoked = 0,
            outstanding = 4,
            ratio = "0.02",
            eta = "—",
            state = TorrentState.Stopping,
        ),
        TorrentRowModel(
            name = "openSUSE-Leap-16.1-DVD-x86_64.iso",
            size = "4.38 GiB",
            progress = 0.63f,
            percent = "63%",
            down = "0",
            up = "0",
            connected = 0,
            unchoked = 0,
            outstanding = 0,
            ratio = "0.19",
            eta = "—",
            state = TorrentState.Error,
        ),
    )
